### ISSUE TITLE
n= slider

### ISSUE THREAD

**Issue by KLBoles** [KLBoles/Manipul8#1]
Slider to increase values of n/patterns generated. Likely some scaling issues here.

**Comment by cproctor** [comment]
This is not super hard to do on the software side. Do you think it would work to have 2 fiducials on either end of the slider frame, and then one on the slider itself? Then we would avoid having to calibrate it; we could just work from relative distance from endpoints.

**Comment by KLBoles** [comment]
That makes sense. Two questions. 

1) How would this calibration be different than the home-cooked version that's already in it?
2) Where on the physical layout do you see the fiducials living so as to not interfere with the other spaces? Between the frame view and pattern view?

**Comment by cproctor** [comment]
1. It would be another layer of calibration. The global calibration is working now, so we can map the space of what the camera sees to the screen space. But if you have only one fiducial on the slider frame, then you're measuring the distance between the frame fiducial and slider fiducial. This will be in units relative to the screen size. So when you change your setup (different camera, physical arrangement, screen size, etc.), you need to re-define some values to specify what the max and min expected distances are for the slider. If you have fiducials on either end of the slider, then you no longer care about units at all; they cancel out. 

2. I can imagine several possibilities. 
   A. Sliders are recognized anywhere on each Pattern View. 
   B. There's a special spot on each Pattern View for each slider. 
   C. What if there were just one slider, that looked kinda like a number line? Then you could put multiple tokens onto it, and each would be a case in a separate Pattern View? You could even just project the number line (so you don't have to make a slider frame mechanism), and detect when tokens are put down. This seems like the best idea to me.

**Comment by cproctor** [comment]
![img_1317](https://user-images.githubusercontent.com/349243/40393958-78314d72-5def-11e8-8895-d0af55d7f3d4.JPG)

**Comment by KLBoles** [comment]
C also makes the most sense to me. This should eliminate some problems of scale, since we can specify and visually limit options on how large n can be, a mathematical compromise, but one that needs to be made. Also, nice drawing! :)

**Comment by cproctor** [comment]
Done in v0.2.1.
