### ISSUE TITLE
Not reading the term/generating pattern.

### ISSUE THREAD

**Issue by KLBoles** [KLBoles/Manipul8#8]
I worked with this some tonight (resized/changed angle), but it's still not reading the term.

![noterm](https://user-images.githubusercontent.com/38933479/40401736-b543bbd4-5dfc-11e8-97c1-8593f78e352b.PNG)

**Comment by KLBoles** [comment]
![nopatternwcamera](https://user-images.githubusercontent.com/38933479/40401899-bc20958e-5dfd-11e8-91e3-d005f31029a8.PNG)

The camera isn't solidly reading the term fiducial (flashes), but I would expect the pattern to show/flash at the time when it reads the term.

**Comment by cproctor** [comment]
First, you'll want to change some settings in Settings to make the whole thing less tiny. This will be a good test to make sure that I've added everything to Settings that belongs there. 

Second, you need to run configuration to match up the camera to the screen. The legit system Bertrand built is working now, so start up the app, press `n`, put a fiducial over each crosshairs, and press `c`. You'll see in the log confirmation that it worked.
